name: Update all four English CSVs from Google Sheets

on:
  schedule:
    - cron: "*/10 * * * *"
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Download latest Enforcement Incidents CSV
        run: curl -L "https://docs.google.com/spreadsheets/d/e/2PACX-1vRl0u5cD7Pqam-o_qXLfxDqxWfQH-icDDA6btfFcvh6dz19HGS5CJHwihBlA00asJTuLTabyhLLI2Aa/pub?gid=1130252425&single=true&output=csv" -o data.csv

      - name: Download latest Detention Facilities CSV
        run: curl -L "https://docs.google.com/spreadsheets/d/e/2PACX-1vRl0u5cD7Pqam-o_qXLfxDqxWfQH-icDDA6btfFcvh6dz19HGS5CJHwihBlA00asJTuLTabyhLLI2Aa/pub?gid=924592835&single=true&output=csv" -o layer2.csv
      
      - name: Download latest Federal Police Facilities CSV
        run: curl -L "https://docs.google.com/spreadsheets/d/e/2PACX-1vRl0u5cD7Pqam-o_qXLfxDqxWfQH-icDDA6btfFcvh6dz19HGS5CJHwihBlA00asJTuLTabyhLLI2Aa/pub?gid=438904366&single=true&output=csv" -o layer3.csv
      
      - name: Download latest Other Police Facilities CSV
        run: curl -L "https://docs.google.com/spreadsheets/d/e/2PACX-1vRl0u5cD7Pqam-o_qXLfxDqxWfQH-icDDA6btfFcvh6dz19HGS5CJHwihBlA00asJTuLTabyhLLI2Aa/pub?gid=718059279&single=true&output=csv" -o layer4.csv
      
      - name: Commit updated CSV
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add data.csv layer2.csv layer3.csv layer4.csv
          git commit -m "Update CSV from Google Sheets" || exit 0
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git HEAD:main

